### ISSUE TITLE
getting error on installation

### ISSUE THREAD

**Issue by dave-letele** [m4ll0k/WPSeku#10]
after writing the command `pip install -r requirements.txt` and then `python wpseku.py` i got this error.
https://prnt.sc/fqlaag

Note that : i have successfully run wpscan and wanted to test this one too but getting error.

**Comment by m4ll0k** [comment]
pip install requests

**Comment by m4ll0k** [comment]
python2.7 wpseku.py

**Comment by dave-letele** [comment]
Thanks :) the installation problem is solved but after i run this command python `wpseku.py --target http://wphack.party --brute --user rasel --wordlist /root/WPSeku/wppass.txt` for buruts force it provide me this output https://pastebin.com/Y5HzVxwd

so it is not trying to login with the username provided and with text file that contain some password.
did i done anything wrong on this command?

Thanks in advance 👍
