### ISSUE TITLE
Target incorrect

### ISSUE THREAD

**Issue by dhd0004** [m4ll0k/WPSeku#14]
I had a problem using the program when Wordpress is not installed in the root of the domain, por example:
https://www.example.com/ <- There is an IIS installed there
https://www.example.com/wordpress/ <- Wordpress installed, maybe in other server.
Uf i use the program with:
python2.7 wpseku.py  --target  "https://www.example.com/wordpress/"

The program try to search the wordpress installation in  "https://www.example.com/ ".
![image](https://user-images.githubusercontent.com/1458162/27823146-63f029d6-60a8-11e7-8c31-8fd5263beeaf.png)

**Comment by m4ll0k** [comment]
python wpseku.py --target http://examples.com --redirect False

**Comment by dhd0004** [comment]
Still not working with the "redirect False".

Regards

**Comment by m4ll0k** [comment]
python2.7 wpseku --target http://examples.com

**Comment by dhd0004** [comment]
The problem is that the target is truncated, and the program just use scheme+domain. In the line 108:
```
def CheckTarget(self,url):
		scheme = urlparse.urlsplit(url).scheme
		netloc = urlparse.urlsplit(url).netloc
		path = urlparse.urlsplit(url).path
		if scheme not in ['http','https','']:
			sys.exit(self.printf.erro('Schme %s not supported'%(scheme)))
		if netloc == "":
			return "http://"+path
		else:
			return scheme+"://"+netloc # if I add here "+path" all works as expected
                        #return scheme+"://"+netloc+path
```

**Comment by m4ll0k** [comment]
modify to so:

def CheckTarget(self,url):
		scheme = urlparse.urlsplit(url).scheme
		netloc = urlparse.urlsplit(url).netloc
		path = urlparse.urlsplit(url).path
		if scheme not in ['http','https','']:
			sys.exit(self.printf.erro('Schme %s not supported'%(scheme)))
		if netloc == "":
			return "http://"+path
		else:
                        return scheme+"://"+netloc+path
