### ISSUE TITLE
Had to do a chmod before it would work

### ISSUE THREAD

**Issue by TorontoBoy** [m4ll0k/WPSeku#16]
I just did a fresh install of WPSeku. To add to your install instructions, when initially trying to run I kept getting "permission denied". I had to do a "sudo chmod 755 wpseku.py" before it would work.

Thanks for the tool.

**Comment by m4ll0k** [comment]
`git clone https://github.com/m4ll0k/WPSeku.git`
`cd WPseku`
`chmod 755 wpseku.py`
`./wpseku.py`

**Comment by MelissaMV** [comment]
I did "chmod 777 wpseku.py" and it worked :)

**Comment by ubaidsworld** [comment]
@m4ll0k  Please close this issue. It is the file permission problem which is solved by assigning th proper rights to the files.
