### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by davidtavarez** [m4ll0k/WPSeku#2]
![wpseku_-____projects_wpseku_001](https://cloud.githubusercontent.com/assets/337107/26514474/12fcaa76-4240-11e7-903b-04bd0d9a538e.png)
![wpseku_-____projects_wpseku_002](https://cloud.githubusercontent.com/assets/337107/26514476/164a3662-4240-11e7-9fcc-5d6544281918.png)

**Comment by davidtavarez** [comment]
Just works with the python prefix
![wpseku_py_-_wpseku_-____projects_wpseku_003](https://cloud.githubusercontent.com/assets/337107/26514566/908ce8e8-4240-11e7-8c3d-274c1cf0d080.png)

**Comment by Redshoee** [comment]
Hi
What's your python version? it's works on python2.7.12

**Comment by davidtavarez** [comment]
$ python --version
Python 2.7.13

**Comment by m4ll0k** [comment]
try with: python2.7 wpseku.py

**Comment by packeteer** [comment]
tested with python 2.7.13 on Alpine Linux in a Docker container. It works fine, thanks!

**Comment by lianfeng30** [comment]
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

**Comment by Droid-MAX** [comment]
![screenshot_20180127-201535](https://user-images.githubusercontent.com/12762435/35513935-92c89428-053f-11e8-8eac-42e12d566e0e.png)

A great software project, It can also be used normally under Termux, very awesome!
