### ISSUE TITLE
Disclosure of script in blog (Brazilian Portuguese)

### ISSUE THREAD

**Issue by tiagoxpl** [m4ll0k/WPSeku#23]
First of all, congratulations to the script and to spread it in the community. It's fantastic!

I created a [post](https://tiagosouza.com/wpseku-scanner-de-vulnerabilidades-para-wordpress/), in Portuguese from Brazil, in my blog about your script (WPSeku). My intention is to spread knowledge and present to the Brazilian public its excellent tool. If at any time you can reference my post, I will be very happy!

When you have news on new tools and scripts, let me know!

Best regards,

**Comment by ubaidsworld** [comment]
@tiagoxpl  Thank you for your information. But this area is for the issues and not for information. If you find it worth then you can edit the repository and pull request. The owner of the repository will decide to merge your request or not. I hope you have got this point.
I request you to close this issue. If @tiagoxpl  doesn't close it, I request the author should close this as it is no issue.
