### ISSUE TITLE
[ ! ] That site not running WordPress

### ISSUE THREAD

**Issue by thistehneisen** [m4ll0k/WPSeku#35]
...but the site is running WordPress, even /wp-admin/ is accessable. Should suggest -f / --force switches for such cases.

**Comment by peratik** [comment]
Me too. I checked by 2 different websites it says: That site not running WordPress

**Comment by BlankShare** [comment]
I had the same problem and i'm pretty sure that the website uses wordpress.
A temporary solution: put a # at the beginning of the string "if 'wordpress' not in _cms_:exit(warn('That site not running WordPress'))" in the file modules/fingerprint/fingerprint.py
