### ISSUE TITLE
open source collaboration

### ISSUE THREAD

**Issue by blshkv** [m4ll0k/WPSeku#4]
Hi, I'm a developer of pentoo linux and trying to compile the best available tools into our distro.
But I'm getting sick of small 1-day projects which just disappears after a short while.

So I have a suggestion for you. Instead of starting a new project, why don't you join an existing project like https://github.com/wpscanteam/wpscan and become its official developer ?

**Comment by m4ll0k** [comment]
how can I do?

**Comment by davidtavarez** [comment]
@blshkv wpscan is working in a new version (https://github.com/wpscanteam/wpscan-v3) but still the code is really hard to understand: a bunch of files with a bunch of line. I think @m4ll0k have a better approach. Personally I'll try to make some pull request, but the core is really solid and the code have a better structure than wpscan, so is easier to contribute.

**Comment by blshkv** [comment]
@m4ll0k just start with contributing, create a pull request.

@davidtavarez ```a bunch of files with a bunch of lines``` LOL?  that's exactly how the source code looks like.

wpscan has a huge database of bugs, just look at wordpresses.json alone, it is 2.5Mb! So I can make a wild guess that it is more compenhasive too

**Comment by blshkv** [comment]
anyway, the purpose of this bug is to bring my 0.5 cents. My job is done ;-) So please forget about it if you disagree. I'll see you in couple years

**Comment by m4ll0k** [comment]
Thank's guys
