### ISSUE TITLE
wpvulndb

### ISSUE THREAD

**Issue by ethicalhack3r** [m4ll0k/WPSeku#9]
Hi!

We're happy that you use the wpvulndb API, but we have a couple of suggestions which would help us a little please :)

Could you add "wpseku" to the user agent string when making requests to the API?

Could you make it clear in the licensing that the wpvulndb data is not Open Source and is a seperate license? Specifically that the API or its data can not be used for commercial purposes without a paid license.

https://wpvulndb.com/api

Thanks!
Ryan

**Comment by m4ll0k** [comment]
Than man

**Comment by m4ll0k** [comment]
thanks man

**Comment by m4ll0k** [comment]
ok

**Comment by m4ll0k** [comment]
I am developing new version of wpseku, i don't use wpvulndb
